(auto-save-mode nil)
(setq make-backup-files nil)
(setq inhibit-startup-screen t)
(setq package-archives '(("gnu"   . "http://elpa.emacs-china.org/gnu/")
                         ("melpa-stable" . "http://elpa.emacs-china.org/melpa-stable/")
                          ("melpa-stable2" . "https://stable.melpa.org/packages/")
                          ("melpa" . "http://elpa.emacs-china.org/melpa/")
                          ("marmalada" . "http://elpa.emacs-china.org/marmalade/")))
(setq-default tab-width 4)
(setq tab-width 4)
(setq indent-tabs-mode nil)
